### ISSUE TITLE
Contribute to Railcraft

### ISSUE THREAD

**Issue by liach** [The-Fireplace/MC-Lang-US-to-UD#1]
I recently noticed that you forked Railcraft to contribute the upside-down language. It seems that you unfortunately failed to find the localization files. They are, in fact, located in https://github.com/Railcraft/Railcraft-Localization . I am looking forward to your contribution.

**Comment by The-Fireplace** [comment]
I saw the railcraft localization, the reason I chose not to do it at this
time is because it uses @ instead of %, ex. @s instead of %s. My script
isn't designed to work with that, and I don't want to manually go through
and fix everything that uses @.

**Comment by liach** [comment]
hmm funny! thanks for your great answer.

**Comment by liach** [comment]
Waiting for your gradle plugin :smile:

**Comment by The-Fireplace** [comment]
See latest commit - it shouldn't be too much longer.

**Comment by The-Fireplace** [comment]
Update: Done!
